/* eslint-disable import/no-anonymous-default-export */
export default [
    {title: 'Denevérek (Bat)', value: 'bat'},
    {title: 'Dűnék-népe (Dunefolk)', value: 'dunefolk'},
    {title: 'Emberek (Human)', value: 'human'},
    {title: 'Élőholtak (Undead)', value: 'undead'},
    {title: 'Fapásztorok (Wose)', value: 'wose'},
    {title: 'Farkasok (Wolf)', value: 'wolf'},
    {title: 'Griffek (Gryphon)', value: 'gryphon'},
    {title: 'Gyíkok (Saurian)', value: 'saurian'},
    {title: 'Koboldok (Goblin)', value: 'goblin'},
    {title: 'Lovak (Horse)', value: 'horse'},
    {title: 'Mechanikus', value: 'mechanical'},
    {title: 'Nagák (Naga)', value: 'naga'},
    {title: 'Ogrék (Ogre)', value: 'ogre'},
    {title: 'Orkok (Orc)', value: 'orc'},
    {title: 'Perzsekények (Drake)', value: 'drake'},
    {title: 'Sellők (Merfolk)', value: 'merfolk'},
    {title: 'Sólymok (Falcon)', value: 'falcon'},
    {title: 'Szörnyek (Monster)',value: 'monster'},
    {title: 'Törpök (Dwarf)', value: 'dwarf'},
    {title: 'Trollok (Troll)', value: 'troll'},
    {title: 'Tündék (Elf)', value: 'elf'},
]